version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7
    commands:
      - pip install -U pip pipenv
      - npm install serverless -g
  pre_build:
    commands:
      - npm install --dev
      - pipenv install
  post_build:
    commands:
      - serverless deploy --stage dev

cache:
  paths:
    - ~/.cache/pip/**/*
    - ./node_modules/**/*