version: 0.2

env:
  variables:
    SLS_DEBUG: 1

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7
    commands:
      - pip install -U pipenv
      - npm install serverless -g
  pre_build:
    commands:
      - npm install --only=dev
  post_build:
    commands:
      - serverless deploy --stage dev -v

cache:
  paths:
    - ~/.cache/pip/**/*
    - ./node_modules/**/*